# Generated by Django 4.2.16 on 2025-07-11 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPredictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_duration', models.FloatField()),
                ('fwd_pkts_tot', models.FloatField()),
                ('bwd_pkts_tot', models.FloatField()),
                ('fwd_data_pkts_tot', models.FloatField()),
                ('bwd_data_pkts_tot', models.FloatField()),
                ('fwd_pkts_per_sec', models.FloatField()),
                ('bwd_pkts_per_sec', models.FloatField()),
                ('flow_pkts_per_sec', models.FloatField()),
                ('down_up_ratio', models.FloatField()),
                ('fwd_header_size_tot', models.FloatField()),
                ('fwd_header_size_min', models.FloatField()),
                ('fwd_header_size_max', models.FloatField()),
                ('bwd_header_size_tot', models.FloatField()),
                ('bwd_header_size_min', models.FloatField()),
                ('bwd_header_size_max', models.FloatField()),
                ('flow_FIN_flag_count', models.IntegerField()),
                ('flow_SYN_flag_count', models.IntegerField()),
                ('flow_RST_flag_count', models.IntegerField()),
                ('fwd_PSH_flag_count', models.IntegerField()),
                ('bwd_PSH_flag_count', models.IntegerField()),
                ('flow_ACK_flag_count', models.IntegerField()),
                ('fwd_URG_flag_count', models.IntegerField()),
                ('bwd_URG_flag_count', models.IntegerField()),
                ('flow_CWR_flag_count', models.IntegerField()),
                ('flow_ECE_flag_count', models.IntegerField()),
                ('fwd_pkts_payload_min', models.FloatField()),
                ('fwd_pkts_payload_max', models.FloatField()),
                ('fwd_pkts_payload_tot', models.FloatField()),
                ('fwd_pkts_payload_avg', models.FloatField()),
                ('fwd_pkts_payload_std', models.FloatField()),
                ('bwd_pkts_payload_min', models.FloatField()),
                ('bwd_pkts_payload_max', models.FloatField()),
                ('bwd_pkts_payload_tot', models.FloatField()),
                ('bwd_pkts_payload_avg', models.FloatField()),
                ('bwd_pkts_payload_std', models.FloatField()),
                ('flow_pkts_payload_min', models.FloatField()),
                ('flow_pkts_payload_max', models.FloatField()),
                ('flow_pkts_payload_tot', models.FloatField()),
                ('flow_pkts_payload_avg', models.FloatField()),
                ('flow_pkts_payload_std', models.FloatField()),
                ('fwd_bulk_packets', models.IntegerField()),
                ('bwd_bulk_packets', models.IntegerField()),
                ('fwd_bulk_rate', models.FloatField()),
                ('bwd_bulk_rate', models.FloatField()),
                ('fwd_init_window_size', models.IntegerField()),
                ('bwd_init_window_size', models.IntegerField()),
                ('fwd_last_window_size', models.IntegerField()),
                ('label', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
